name: deploy

on:
  workflow_call:
  
jobs:
  my-job-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!" 
      - name: print-multiple
        run: | 
          echo github.event_name = ${{ github.event_name }}
          echo github.event.issue.pull_request = ${{ github.event.issue.pull_request }}
          echo github.event.comment.body = ${{ github.event.comment.body }}


