name: testvariable

on:
  workflow_dispatch:
    inputs: 
      fetchcore-version:
        description: "version of the fetchcore"
        default: 11.0.0-20230809.77
        type: choice
      fetchcore-instance-name:
        description: "Name of the fetchcore instance" 
        type: choice

jobs: 
  check_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Check if variable is set
        run: |
          if [ -z "${{ inputs.fetchcore_instance_name }}" ]; then
            echo "Variable 'fetchcore-instance-name' not set. Setting it..."
            echo "fetchcore_instance_name=${{ inputs.fetchcore_version }}-${{ inputs.fetchcore_instance_name }}" >> $GITHUB_ENV
          else
            echo "Variable 'fetchcore-instance-name' is already set."

  print_variable:
    needs: check_variable
    runs-on: ubuntu-latest
    steps:
      - name: Print the variable
        run: |
           echo "fetchcore_instance_name: ${{ inputs.fetchcore_instance_name }}"           
           echo "fetchcore_instance_name: ${{ env.fetchcore_instance_name }}"
